docs/openapi/api-external-b2b-pa-v1.yaml, docs/openapi/api-internal-b2b-pa-v1.yaml
- eseguite piccole correzioni ortografiche
- aggiunta la FAQ del forbidden che indirizza alla mail dell'onboarding
- aggiunta la FAQ sul tempo di mantenimento documenti fra upload ed invio notifica
- aggiunta la FAQ sulla distinzione atti tra PF e PG
- applicato collapsible su tutte le domande/risposte per permettere una migliore leggibilità
- sincrinizzate versioni internal-external
=> Aggiornamento Swagger

scripts/aws/cfn/microservice.yml, scripts/aws/cfn/storage.yml
=> PN Delivery dashboard

docs/openapi/api-internal-b2b-pa-v1.yaml
- aggiunta FAQ su upload documento verso S3
=> aggiornamento file Swagger

scripts/aws/cfn/microservice.yml
Provided kinesis source stream arn to api gwy stack
=> Kinesis source stream to api gwy

scripts/aws/cfn/microservice.yml
Sent lambda logs to kinesis stream
=> PN-2746: sending lambda logs to kinesis stream

scripts/aws/cfn/microservice.yml
=> PN-2657: Added rest api latency alarm

scripts/aws/cfn/microservice.yml
=> PN-2898: removed comments about managed policy

scripts/aws/cfn/microservice.yml
=> PN-2732: added AlbSecurityGroup parameter

docs/openapi/api-external-b2b-pa-bundle.yaml, docs/openapi/remote-refs.yaml, pom.xml
- Modificato commitId del link dell'openapi di delievry push
- eseguito script internal-to-external
=> adeguato openapi di delivery-push

docs/openapi/api-external-b2b-pa-v1.yaml, docs/openapi/api-internal-b2b-pa-v1.yaml
sul servizio healt check inserito "# il servizio è ancora in fase di sviluppo"
=> Modifiche file swagger:

docs/openapi/api-external-b2b-pa-v1.yaml, docs/openapi/api-internal-b2b-pa-v1.yaml
Modifica alle faq sulla simulazione dell'upload di un documento su S3
=> aggiornamento filw swagger:

config/application.properties, src/main/java/it/pagopa/pn/delivery/middleware/notificationdao/DtoToEntityNotificationMapper.java, src/main/java/it/pagopa/pn/delivery/middleware/notificationdao/EntityToDtoNotificationMapper.java, src/main/java/it/pagopa/pn/delivery/middleware/notificationdao/entities/F24PaymentEntity.java, src/main/java/it/pagopa/pn/delivery/middleware/notificationdao/entities/MetadataAttachmentEntity.java, src/main/java/it/pagopa/pn/delivery/middleware/notificationdao/entities/NotificationPaymentInfoEntity.java, src/main/java/it/pagopa/pn/delivery/middleware/notificationdao/entities/NotificationRecipientEntity.java, src/main/java/it/pagopa/pn/delivery/middleware/notificationdao/entities/PagoPaPaymentEntity.java, src/main/java/it/pagopa/pn/delivery/models/internal/notification/F24Payment.java, src/main/java/it/pagopa/pn/delivery/rest/PnReceivedNotificationsController.java, src/main/java/it/pagopa/pn/delivery/svc/NotificationAttachmentService.java, src/main/java/it/pagopa/pn/delivery/svc/search/NotificationRetrieverService.java, src/test/java/it/pagopa/pn/delivery/middleware/notificationdao/EntityToDtoNotificationMapperTest.java
Allineate alcune entità dei pagamenti rispetto allo stile utilizzato per le altre entità delle notifiche. Aggiunti log per api di download attachments
=> Fix notification entities

docs/openapi/api-private.yaml, docs/openapi/schemas-pn-timeline-appio.yaml, src/main/java/it/pagopa/pn/delivery/rest/PnInternalNotificationsController.java, src/main/java/it/pagopa/pn/delivery/rest/PnReceivedNotificationsController.java, src/main/java/it/pagopa/pn/delivery/rest/PnSentNotificationsController.java, src/main/java/it/pagopa/pn/delivery/svc/NotificationAttachmentService.java, src/main/java/it/pagopa/pn/delivery/utils/io/IOMapper.java, src/test/java/it/pagopa/pn/delivery/rest/PnInternalNotificationsControllerTest.java, src/test/java/it/pagopa/pn/delivery/utils/io/IOMapperTest.java
aligned download attachment private api and added category in third party attachment schema
=> Aligned download attachment private api

src/main/java/it/pagopa/pn/delivery/middleware/notificationdao/DtoToEntityNotificationMapper.java
..... della tabella pn-Notifications
=> PN-9183 ripristino della corretta del campo sourceChannelDetails 

config/application.properties, scripts/aws/cfn/microservice.yml, scripts/aws/cfn/storage.yml, src/main/java/it/pagopa/pn/delivery/PnDeliveryConfigs.java, src/main/java/it/pagopa/pn/delivery/exception/PnDeliveryExceptionCodes.java, src/main/java/it/pagopa/pn/delivery/middleware/notificationdao/PaNotificationLimitDao.java, src/main/java/it/pagopa/pn/delivery/middleware/notificationdao/PaNotificationLimitDaoDynamo.java, src/main/java/it/pagopa/pn/delivery/middleware/notificationdao/entities/PaNotificationLimitEntity.java, src/main/java/it/pagopa/pn/delivery/svc/PaNotificationLimitService.java, src/test/java/it/pagopa/pn/delivery/middleware/notificationdao/PaNotificationLimitDaoDynamoTest.java, src/test/java/it/pagopa/pn/delivery/svc/PaNotificationLimitServiceTest.java, src/test/resources/testcontainers/init.sh
[PN-13902] - PaNotificationLimitService for table paNotificationLimit
[PN-13902]: https://pagopa.atlassian.net/browse/PN-13902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PN-13902] - PaNotificationLimitService for table paNotificationLimit

config/application.properties, scripts/aws/cfn/microservice.yml, scripts/aws/cfn/storage.yml, src/main/java/it/pagopa/pn/delivery/PnDeliveryConfigs.java, src/main/java/it/pagopa/pn/delivery/exception/PnDeliveryExceptionCodes.java, src/main/java/it/pagopa/pn/delivery/middleware/notificationdao/PaNotificationLimitDao.java, src/main/java/it/pagopa/pn/delivery/middleware/notificationdao/PaNotificationLimitDaoDynamo.java, src/main/java/it/pagopa/pn/delivery/middleware/notificationdao/entities/PaNotificationLimitEntity.java, src/main/java/it/pagopa/pn/delivery/svc/NotificationReceiverService.java, src/main/java/it/pagopa/pn/delivery/svc/PaNotificationLimitService.java, src/test/java/it/pagopa/pn/delivery/middleware/notificationdao/PaNotificationLimitDaoDynamoTest.java, src/test/java/it/pagopa/pn/delivery/svc/NotificationReceiverTest.java, src/test/java/it/pagopa/pn/delivery/svc/PaNotificationLimitServiceTest.java, src/test/resources/testcontainers/init.sh
[PN-13903] - Modified NotificationReceiverService to manage new logic for notification limit
[PN-13903]: https://pagopa.atlassian.net/browse/PN-13903?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PN-13903] - Modified NotificationReceiverService to manage new logic for notification limit

src/main/java/it/pagopa/pn/delivery/middleware/notificationdao/NotificationRefusedVerificationDaoDynamo.java, src/main/java/it/pagopa/pn/delivery/svc/NotificationReceiverService.java, src/main/java/it/pagopa/pn/delivery/svc/PaNotificationLimitService.java
[PN-13802] - Fix logs
[PN-13802]: https://pagopa.atlassian.net/browse/PN-13802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PN-13802] - Fix logs

functions/paLimitCorrection/src/app/lib/processDate.js, functions/paLimitCorrection/src/test/processDate.test.js, scripts/aws/cfn/microservice-dev-cfg.json, scripts/aws/cfn/microservice.yml
[PN-14170] - Added DEBUG_MODE variable to PaLimitCorrectionLambda
[PN-14170]: https://pagopa.atlassian.net/browse/PN-14170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PN-14170] - Added DEBUG_MODE variable to PaLimitCorrectionLambda

functions/paLimitCorrection/src/app/lib/dynamo.js, functions/paLimitCorrection/src/app/lib/processDate.js, functions/paLimitCorrection/src/app/lib/slaLambda.js, functions/paLimitCorrection/src/test/processDate.test.js, functions/paLimitCorrection/src/test/slaLambda.test.js
[PN-13802] - Fix out of memory paLimitCorrectionLambda
[PN-13802]: https://pagopa.atlassian.net/browse/PN-13802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PN-13802] - Fix out of memory paLimitCorrectionLambda

functions/paLimitCorrection/package-lock.json, functions/paLimitCorrection/package.json, functions/paLimitCorrection/src/app/lib/cloudWatch.js, functions/paLimitCorrection/src/app/lib/processDate.js, functions/paLimitCorrection/src/test/cloudWatch.test.js, functions/paLimitCorrection/src/test/processDate.test.js, scripts/aws/cfn/microservice.yml
[PN-14213] - Added CloudWatch IteratorAge metrics and integrated with pa limit correction logic
[PN-14213]: https://pagopa.atlassian.net/browse/PN-14213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PN-14213] - Added CloudWatch IteratorAge metrics and integrated with pa limit correction logic
